//
// Generated file, do not edit! Created by nedtool 5.6 from pocMsg.msg.
//

#ifndef __POCMSG_M_H
#define __POCMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>pocMsg.msg:17</tt> by nedtool.
 * <pre>
 * message PocMsg extends cPacket
 * {
 *     int source;
 *     int destination;
 *     string msgContent;
 *     int hopCount = 0;
 *     string datas;
 * }
 * </pre>
 */
class PocMsg : public ::omnetpp::cPacket
{
  protected:
    int source;
    int destination;
    ::omnetpp::opp_string msgContent;
    int hopCount;
    ::omnetpp::opp_string datas;

  private:
    void copy(const PocMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PocMsg&);

  public:
    PocMsg(const char *name=nullptr, short kind=0);
    PocMsg(const PocMsg& other);
    virtual ~PocMsg();
    PocMsg& operator=(const PocMsg& other);
    virtual PocMsg *dup() const override {return new PocMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual const char * getMsgContent() const;
    virtual void setMsgContent(const char * msgContent);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
    virtual const char * getDatas() const;
    virtual void setDatas(const char * datas);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PocMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PocMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __POCMSG_M_H

